project/__init__.py
from flask import Flask, render_template


######################################
#### Application Factory Function ####
######################################

def create_app():
    # Create the Flask application
    app = Flask(__name__)

    register_blueprints(app)
    register_error_pages(app)
    return app


########################
### Helper Functions ###
########################

def register_blueprints(app):
    # Import the blueprints
    from project.recipes import recipes_blueprint
    from project.blog import blog_blueprint

    # Since the application instance is now created, register each Blueprint
    # with the Flask application instance (app)
    app.register_blueprint(recipes_blueprint)
    app.register_blueprint(blog_blueprint)


def register_error_pages(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

project/blog/__init__.py
"""
The `blog` blueprint handles displaying blog posts.
"""
from flask import Blueprint

blog_blueprint = Blueprint('blog', __name__, template_folder='templates')

from . import routes

project/blog/routes.py
from . import blog_blueprint
from flask import render_template, abort


blog_post_titles = ['kitchenaid_mixer', 'measuring_cups', 'air_fryer']


@blog_blueprint.route('/blog/')
def blog():
    return render_template('blog/blog.html')


@blog_blueprint.route('/blog/<blog_title>/')
def posts(blog_title):
    if blog_title not in blog_post_titles:
        abort(404)

    return render_template(f'blog/{blog_title}.html')


@blog_blueprint.route('/about/')
def about():
    return render_template('blog/about.html')

project/recipes/__init__.py
"""
The `recipes` blueprint handles displaying recipes.
"""
from flask import Blueprint

recipes_blueprint = Blueprint('recipes', __name__, template_folder='templates')

from . import routes

project/recipes/routes.py
from . import recipes_blueprint
from flask import render_template, abort


breakfast_recipes_names = ['pancakes', 'acai_bowl', 'honey_bran_muffins', 'breakfast_scramble',
                           'pumpkin_donuts', 'waffles', 'omelette', 'chocolate_donuts', 'oatmeal',
                           'morning_glory_muffins', 'blueberry_smoothie_bowl']
dinner_recipes_names = ['steak_fajitas', 'ground_beef_tacos', 'pizza', 'sweet_fire_chicken', 'tri_tip',
                        'shredded_chicken', 'taquitos', 'red_lentil_chili']
baked_goods_recipes_names = ['bagels', 'french_bread', 'pitas', 'irish_soda_bread', 'soft_rolls',
                             'pizza_dough', 'pitas2', 'banana_bread', 'scones']
side_dishes_recipes_names = ['sweet_potatoes', 'spanish_rice', 'jasmine_rice', 'fruit_salad']
dessert_recipes_names = ['brownies', 'chocolate_chip_cookies', 'linzer_cookies', 'sugar_cookies',
                         'flourless_chocolate_cake']
drink_recipes_names = ['berry_smoothie', 'chocolate_milk_shake', 'apple_cider_vinegar_drink']


@recipes_blueprint.route('/')
def recipes():
    return render_template('recipes/recipes.html',
                           number_of_breakfast_recipes=len(breakfast_recipes_names),
                           number_of_dinner_recipes=len(dinner_recipes_names),
                           number_of_baked_goods_recipes=len(baked_goods_recipes_names),
                           number_of_side_dishes_recipes=len(side_dishes_recipes_names),
                           number_of_dessert_recipes=len(dessert_recipes_names),
                           number_of_drink_recipes=len(drink_recipes_names))


@recipes_blueprint.route('/breakfast/')
def breakfast_recipes():
    return render_template('recipes/breakfast.html')


@recipes_blueprint.route('/breakfast/<recipe_name>/')
def breakfast_recipe(recipe_name):
    if recipe_name not in breakfast_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/dinner/')
def dinner_recipes():
    return render_template('recipes/dinner.html')


@recipes_blueprint.route('/dinner/<recipe_name>/')
def dinner_recipe(recipe_name):
    if recipe_name not in dinner_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/baked_goods/')
def baked_goods_recipes():
    return render_template('recipes/baked_goods.html')


@recipes_blueprint.route('/baked_goods/<recipe_name>/')
def baked_goods_recipe(recipe_name):
    if recipe_name not in baked_goods_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/side_dishes/')
def side_dishes_recipes():
    return render_template('recipes/side_dishes.html')


@recipes_blueprint.route('/side_dishes/<recipe_name>/')
def side_dishes_recipe(recipe_name):
    if recipe_name not in side_dishes_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/dessert/')
def dessert_recipes():
    return render_template('recipes/dessert.html')


@recipes_blueprint.route('/dessert/<recipe_name>/')
def dessert_recipe(recipe_name):
    if recipe_name not in dessert_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/drink/')
def drink_recipes():
    return render_template('recipes/drink.html')


@recipes_blueprint.route('/drink/<recipe_name>/')
def drink_recipe(recipe_name):
    if recipe_name not in drink_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Flask Recipe App</title>

        <!-- Local CSS file for styling the application-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base_style.css') }}">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">

        <!-- Additional Styling -->
        {% block styling %}
        {% endblock %}
    </head>

    <body>
        <header>
            <h1>Kennedy Family Recipes</h1>
            <nav>
                <ul>
                    <li class="nav__item"><a href="{{ url_for('recipes.recipes') }}" class="nav__link">Recipes</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.blog') }}" class="nav__link">Blog</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.about') }}" class="nav__link">About</a></li>
                </ul>
            </nav>
        </header>

        <main class="content">
            <!-- child template -->
            {% block content %}
            {% endblock %}
        </main>

        <footer>
            <p>Created by <a href="https://www.patricksoftwareblog.com/">Patrick Kennedy</a> (2023)</p>
        </footer>
    </body>
</html>

project/templates/blogpost.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blogpost_style.css') }}">
{% endblock %}

{% block content %}
<div class="blogpost-container card-overlay">
    <div class="blogpost__heading">
        {% block title %}
        {% endblock %}

        <h3>by Patrick Kennedy</h3>

        {% block date %}
        {% endblock %}
    </div>

    <div class="blogpost__image">
        {% block image %}
        {% endblock %}
    </div>

    <div class="blogpost__article">
        {% block article %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/recipe.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">
    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/recipe2.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">

    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}