project/recipes/__init__.py
"""
The `recipes` blueprint handles displaying recipes.
"""
from flask import Blueprint

recipes_blueprint = Blueprint('recipes', __name__, template_folder='templates')

from . import routes

project/recipes/routes.py
from . import recipes_blueprint
from flask import render_template, abort


breakfast_recipes_names = ['pancakes', 'acai_bowl', 'honey_bran_muffins', 'breakfast_scramble',
                           'pumpkin_donuts', 'waffles', 'omelette', 'chocolate_donuts', 'oatmeal',
                           'morning_glory_muffins', 'blueberry_smoothie_bowl']
dinner_recipes_names = ['steak_fajitas', 'ground_beef_tacos', 'pizza', 'sweet_fire_chicken', 'tri_tip',
                        'shredded_chicken', 'taquitos', 'red_lentil_chili']
baked_goods_recipes_names = ['bagels', 'french_bread', 'pitas', 'irish_soda_bread', 'soft_rolls',
                             'pizza_dough', 'pitas2', 'banana_bread', 'scones']
side_dishes_recipes_names = ['sweet_potatoes', 'spanish_rice', 'jasmine_rice', 'fruit_salad']
dessert_recipes_names = ['brownies', 'chocolate_chip_cookies', 'linzer_cookies', 'sugar_cookies',
                         'flourless_chocolate_cake']
drink_recipes_names = ['berry_smoothie', 'chocolate_milk_shake', 'apple_cider_vinegar_drink']


@recipes_blueprint.route('/')
def recipes():
    return render_template('recipes/recipes.html',
                           number_of_breakfast_recipes=len(breakfast_recipes_names),
                           number_of_dinner_recipes=len(dinner_recipes_names),
                           number_of_baked_goods_recipes=len(baked_goods_recipes_names),
                           number_of_side_dishes_recipes=len(side_dishes_recipes_names),
                           number_of_dessert_recipes=len(dessert_recipes_names),
                           number_of_drink_recipes=len(drink_recipes_names))


@recipes_blueprint.route('/breakfast/')
def breakfast_recipes():
    return render_template('recipes/breakfast.html')


@recipes_blueprint.route('/breakfast/<recipe_name>/')
def breakfast_recipe(recipe_name):
    if recipe_name not in breakfast_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/dinner/')
def dinner_recipes():
    return render_template('recipes/dinner.html')


@recipes_blueprint.route('/dinner/<recipe_name>/')
def dinner_recipe(recipe_name):
    if recipe_name not in dinner_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/baked_goods/')
def baked_goods_recipes():
    return render_template('recipes/baked_goods.html')


@recipes_blueprint.route('/baked_goods/<recipe_name>/')
def baked_goods_recipe(recipe_name):
    if recipe_name not in baked_goods_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/side_dishes/')
def side_dishes_recipes():
    return render_template('recipes/side_dishes.html')


@recipes_blueprint.route('/side_dishes/<recipe_name>/')
def side_dishes_recipe(recipe_name):
    if recipe_name not in side_dishes_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/dessert/')
def dessert_recipes():
    return render_template('recipes/dessert.html')


@recipes_blueprint.route('/dessert/<recipe_name>/')
def dessert_recipe(recipe_name):
    if recipe_name not in dessert_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')


@recipes_blueprint.route('/drink/')
def drink_recipes():
    return render_template('recipes/drink.html')


@recipes_blueprint.route('/drink/<recipe_name>/')
def drink_recipe(recipe_name):
    if recipe_name not in drink_recipes_names:
        abort(404)

    return render_template(f'recipes/{recipe_name}.html')

project/recipes/templates/recipes/acai_bowl.html
{% extends "recipe.html" %}

{% block recipe_title %}
<h1>Acai Bowl</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>An Acai Bowl with fresh fruit and granola is my favorite breakfast!  It's delicious, refreshing, and hydrating!</p>
<p>I've been making smoothies for years, but making a thick smoothie using frozen Acai and turning it into an Acai bowl is something I recently discovered.</p>
<p>I don't understand why, but I always feel so hydrated after eating an Acai Bowl.</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/acai_bowl.jpg') }}"  alt="Acai Bowl" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>Use your favorite granola as a topping.  I've found that a granola with banana chips goes perfect in an Acai Bowl.</p>
<p>Fresh fruit is an idea topping during the summer months when strawberries and blueberries are in season.  During off-seasons, using granola as the only topping works well.</p>
<p>It can be tough to get the correct consistency in the blender, but add water if the mixture is too thick and isn't mixing correctly.</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
    <li>1 Packet of Frozen Unsweetened Acai</li>
    <li>1 Cup of Frozen Blueberries</li>
    <li>1 Cup of Frozen Strawberries</li>
    <li>1/3 Cup of Frozen Dark Cherries</li>
    <li>1 Fresh Banana</li>
    <li>1 Cup of Water</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
    <li>Using a blender, start by adding the Water and then all of the frozen fruit</li>
    <li>Add the banana to the blender by breaking it up into pieces (3 or 4)</li>
    <li>Blend on a medium speed until the mixture is smooth and everything is incorporated together</li>
    <li>Add more water to the blender if the mixture is too thick</li>
    <li>Pour the thick mixture into a bowl and top with your favorite toppings (fresh fruit, granola)</li>
</ol>
{% endblock %}

project/recipes/templates/recipes/apple_cider_vinegar_drink.html
{% extends "recipe.html" %}

{% block recipe_title %}
<h1>Apple Cider Vinegar Drink</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>This drink is the best way that I've found to drink apple cider vinegar (ACV), as it has a very harsh and acidic taste.</p>
<p>Apple cider vinegar has a number of <a href="https://health.clevelandclinic.org/exploring-the-health-benefits-of-apple-cider-vinegar/">health benefits</a>, including lower blood sugar and promoting weight loss.  I've found it to be really beneficial for my digestive health.</p>
<p>The agave nectar in this drink makes it slightly sweet, so it almost tastes like drinking an applie pie.</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/apple_cider_vinegar_drink.jpg') }}"  alt="Apple Cider Vinegar Drink" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>Try to disolve/mix the cinnamon in hot water before adding any other ingredients, as the cinnamon can really clump up in liquid.</p>
<p>Since apple cider vinegar is so acidic, it's best to drink this drink with a straw to avoid the acidity affecting your teeth if you were to drink it straight from a cup.</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
    <li>1 Teaspoon of Ground Cinnamon</li>
    <li>4 Fluid Ounces of Hot Water</li>
    <li>2 Tablespoons of Apple Cider Vinegar (ACV)</li>
    <li>1 Tablespoon of Agave Nectar (or Maple Syrup)</li>
    <li>1 Cup of Ice</li>
    <li>20 Fluid Ounces of Cold Water</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
    <li>This drink makes about 25 fluid ounces, so start by using a large cup or a <a href="https://www.target.com/p/ball-32oz-12pk-glass-regular-mouth-mason-jar-with-lid-and-band/-/A-12911372#lnk=sametab">large mason jar.</a></li>
    <li>Add the cinnamon and hot water to the cup and mix thoroughly with a spoon.</li>
    <li>Add the Apple Cider Vinegar (ACV) and Agave Nectar (or Maple Syrup).</li>
    <li>Add the ice and cold water to the cup and mix thoroughly.</li>
    <li>Enoy with a straw!</li>
</ol>
{% endblock %}

project/recipes/templates/recipes/blueberry_smoothie_bowl.html
{% extends "recipe.html" %}

{% block recipe_title %}
<h1>Blueberry Smoothie Bowl</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>A blueberry smoothie bowl is one of my favorite breakfasts!  I love the mixture of banana and blueberries to create the base of the bowl.</p>
<p>This smoothie bowl can be topped with your favorite toppings, such as granola, fresh fruit, coconut flakes, flaxseeds, etc.</p>
<p>I find having a smoothie bowl like this for breakfast really helps to hydrate me for the day and gives me energy for the morning.</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/blueberry_smoothie_bowl.jpg') }}" alt="Blueberry Smoothie Bowl" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>I like to add as little almond milk (the liquid) as possible into the blender to make the smoothie thick.  Even with a high-speed blender, I find that I need to use a spatula to mix up the smoothie in the blender to help everything get combined.</p>
<p>Water can be used instead of almond milk, but I find that the almond milk helps with the taste and consistency.</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
<li>1 large banana</li>
<li>1.5 cups of frozen blueberries (I really like using wild blueberries, which are smaller than normal blueberries)</li>
<li>1/4 cup of almond milk</li>
<li>Toppings: fresh fruit, granola, coconut flakes, flaxseeds, etc.</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
<li>Add the banana, frozen blueberries, and almond milk to a blender.</li>
<li>Blend until well combined and the frozen blueberries are completely mixed into the smoothie mixture.  I find I need to stop the blender, use a spatula to mix up the smoothie, and then blend some more.</li>
<li>Scoop smoothie mixture into a bowl and add your favorite toppings.  Enjoy!</li>
</ol>
{% endblock %}

project/recipes/templates/recipes/breakfast.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='pancakes') }}">
            <img
              src="{{ url_for('static', filename='img/pancakes.jpg') }}"
              alt="Pancakes"
              class="card__image" />
            <div class="card__body">
                <h2>Pancakes</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='honey_bran_muffins') }}">
            <img
              src="{{ url_for('static', filename='img/honey_bran_muffins.jpg') }}"
              alt="Honey Bran Muffins"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Honey Bran Muffins</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='acai_bowl') }}">
            <img
              src="{{ url_for('static', filename='img/acai_bowl.jpg') }}"
              alt="Acai Bowl"
              class="card__image" />
            <div class="card__body">
                <h2>Acai Bowl</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='breakfast_scramble') }}">
            <img
              src="{{ url_for('static', filename='img/breakfast_scramble.jpg') }}"
              alt="Breakfast Scramble"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Breakfast Scramble</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='pumpkin_donuts') }}">
            <img
              src="{{ url_for('static', filename='img/pumpkin_donuts.jpg') }}"
              alt="Pumpkin Donuts"
              class="card__image" />
            <div class="card__body">
                <h2>Pumpkin Donuts</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='waffles') }}">
            <img
              src="{{ url_for('static', filename='img/waffles.jpg') }}"
              alt="Waffles"
              class="card__image" />
            <div class="card__body">
                <h2>Waffles</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='omelette') }}">
            <img
              src="{{ url_for('static', filename='img/omelette.jpg') }}"
              alt="Omelette"
              class="card__image" />
            <div class="card__body">
                <h2>Omelette</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='chocolate_donuts') }}">
            <img
              src="{{ url_for('static', filename='img/chocolate_donuts.jpg') }}"
              alt="Chocolate Donuts"
              class="card__image" />
            <div class="card__body">
                <h2>Chocolate Donuts</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='oatmeal') }}">
            <img
              src="{{ url_for('static', filename='img/oatmeal.jpg') }}"
              alt="Oatmeal"
              class="card__image" />
            <div class="card__body">
                <h2>Oatmeal</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='morning_glory_muffins') }}">
            <img
              src="{{ url_for('static', filename='img/morning_glory_muffins.jpg') }}"
              alt="Morning Glory Muffins"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Morning Glory Muffins</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.breakfast_recipe', recipe_name='blueberry_smoothie_bowl') }}">
            <img
              src="{{ url_for('static', filename='img/blueberry_smoothie_bowl.jpg') }}"
              alt="Blueberry Smoothie Bowl"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-extra-long">Blueberry Smoothie Bowl</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/dinner.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='steak_fajitas') }}">
            <img
              src="{{ url_for('static', filename='img/steak_fajitas.jpg') }}"
              alt="Steak Fajitas"
              class="card__image" />
            <div class="card__body">
                <h2>Steak Fajitas</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='ground_beef_tacos') }}">
            <img
              src="{{ url_for('static', filename='img/ground_beef_tacos.jpg') }}"
              alt="Ground Beef Tacos"
              class="card__image" />
            <div class="card__body">
                <h2>Ground Beef Tacos</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='pizza') }}">
            <img
              src="{{ url_for('static', filename='img/pizza.jpg') }}"
              alt="Pizza"
              class="card__image" />
            <div class="card__body">
                <h2>Pizza</h2>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='sweet_fire_chicken') }}">
            <img
              src="{{ url_for('static', filename='img/sweet_fire_chicken.jpg') }}"
              alt="Sweet Fire Chicken"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Sweet Fire Chicken</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='tri_tip') }}">
            <img
              src="{{ url_for('static', filename='img/tri_tip.jpg') }}"
              alt="Tri-Tip"
              class="card__image" />
            <div class="card__body">
                <h2>Tri-Tip</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='shredded_chicken') }}">
            <img
              src="{{ url_for('static', filename='img/shredded_chicken.jpg') }}"
              alt="Shredded Chicken"
              class="card__image" />
            <div class="card__body">
                <h2>Shredded Chicken</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='taquitos') }}">
            <img
              src="{{ url_for('static', filename='img/taquitos.jpg') }}"
              alt="Taquitos"
              class="card__image" />
            <div class="card__body">
                <h2>Taquitos</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.dinner_recipe', recipe_name='red_lentil_chili') }}">
            <img
              src="{{ url_for('static', filename='img/red_lentil_chili.jpg') }}"
              alt="Red Lentil Chili"
              class="card__image" />
            <div class="card__body">
                <h2>Red Lentil Chili</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/recipes/templates/recipes/flourless_chocolate_cake.html
{% extends "recipe.html" %}

{% block recipe_title %}
<h1>Flourless Chocolate Cake</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>This delicious cake is an incredible dessert, plus it's gluten-free!  This cake is fudgy and chocolate-y, as it is similar in texture to a brownie.</p>
<p>The dusting of powdered sugar on the top of the cake is both decorative and adds a nice sweetness.</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/flourless_chocolate_cake.jpg') }}" alt="Flourless Chocolate Cake" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>Be patient and take your time with the double-boiler when melting the chocolate and the butter.  The melting process should take 5-10 minutes.</p>
<p>Use a sift for adding the cocoa powder into the batter and also for dusting the cake at the end with powdered sugar.  The whisk really helps to break up any pieces and results in a smooth, uniform texture/finish.</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
<li>4 ounces of Bittersweet Chocolate (not unsweetened)</li>
<li>1 stick of Dairy-Free Butter (recommendation: <a href="https://www.earthbalancenatural.com/spreads/soy-free-buttery-spread">Earth Balance - Soy Free Butter Spread</a>)</li>
<li>0.75 cups of Granulated Sugar</li>
<li>3 large Eggs</li>
<li>0.5 cups of Unsweetened Cocoa Powder</li>
<li>Powdered Sugar (for sprinkling cake after baking)</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
<li>Preheat oven to 375°F and butter an 9-inch round baking pan. Line bottom with a round of parchment paper and butter paper.</li>
<li>In a double boiler or metal mixing bowl set over a saucepan of barely simmering water, slowly melt the chocolate with the butter, stirring, until smooth (about 5-10 minutes).</li>
<li>Remove top of double boiler or bowl from heat and whisk in the sugar into the chocolate mixture.</li>
<li>Add Eggs and whisk well (to prevent the eggs from cooking).</li>
<li>Sift cocoa powder into the chocolate mixture and whisk until just combined.</li>
<li>Pour batter into the prepared pan and bake for 20  minutes, or until the top has formed a thin crust.</li>
<li>Cool the cake in pan on a rack 5 minutes.</li>
<li>Run a butter knife around the side of the cake and then invert onto a serving plate.</li>
<li>Dust cake with powdered sugar.</li>
</ol>
{% endblock %}

project/recipes/templates/recipes/fruit_salad.html
{% extends "recipe.html" %}

{% block recipe_title %}
<h1>Fruit Salad</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>I love having a fruit salad as a side dish with lunch or an afternoon snack.</p>
<p>Fruit salads are best to make in the spring and summer when fresh fruit is in season.</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/fruit_salad.jpg') }}" alt="Fruit Salad" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>I like having a very liquid-y fruit as the base of my fruit salad, so pineapple or watermelon are my favorite base fruits for this salad.  The extra liquid from these fruits help to </p>
<p>Pick your favorite fruits to add to a fruit salad!</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<h4>Fresh Fruit ... options:</h4>
<ul>
<li>Watermelon</li>
<li>Pineapple</li>
<li>Blueberries</li>
<li>Strawberries</li>
<li>Grapes</li>
<li>Peaches</li>
<li>Nectarines</li>
<li>Apples</li>
<li>Pears</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
<li>Cut up fruit into bite-sized pieces and place in a serving bowl or individual bowls.</li>
<li>After all the fruit is cut up, mix the fruit pieces together to get the natural fruit juices to mix with all the fruit.</li>
<li>Enjoy right away or store in the refrigerator for up to 2 days!</li>
</ol>
{% endblock %}

project/recipes/templates/recipes/side_dishes.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('recipes.side_dishes_recipe', recipe_name='sweet_potatoes') }}">
            <img
              src="{{ url_for('static', filename='img/sweet_potatoes.jpg') }}"
              alt="Sweet Potatoes"
              class="card__image" />
            <div class="card__body">
                <h2>Sweet Potatoes</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.side_dishes_recipe', recipe_name='spanish_rice') }}">
            <img
              src="{{ url_for('static', filename='img/spanish_rice.jpg') }}"
              alt="Spanish Rice"
              class="card__image" />
            <div class="card__body">
                <h2>Spanish Rice</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.side_dishes_recipe', recipe_name='jasmine_rice') }}">
            <img
              src="{{ url_for('static', filename='img/jasmine_rice.jpg') }}"
              alt="Jasmine Rice"
              class="card__image" />
            <div class="card__body">
                <h2>Jasmine Rice</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('recipes.side_dishes_recipe', recipe_name='fruit_salad') }}">
            <img
              src="{{ url_for('static', filename='img/fruit_salad.jpg') }}"
              alt="Fruit Salad"
              class="card__image" />
            <div class="card__body">
                <h2>Fruit Salad</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}