project/blog/__init__.py
"""
The `blog` blueprint handles displaying blog posts.
"""
from flask import Blueprint

blog_blueprint = Blueprint('blog', __name__, template_folder='templates')

from . import routes

project/blog/routes.py
from . import blog_blueprint
from flask import render_template, abort


blog_post_titles = ['kitchenaid_mixer', 'measuring_cups', 'air_fryer']


@blog_blueprint.route('/blog/')
def blog():
    return render_template('blog/blog.html')


@blog_blueprint.route('/blog/<blog_title>/')
def posts(blog_title):
    if blog_title not in blog_post_titles:
        abort(404)

    return render_template(f'blog/{blog_title}.html')


@blog_blueprint.route('/about/')
def about():
    return render_template('blog/about.html')

project/blog/templates/blog/about.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blogpost_style.css') }}">
{% endblock %}

{% block content %}
<div class="blogpost-container card-overlay">

    <div class="blogpost__article">
        <h1>About</h1>

        <h2>Recipes</h2>
        <p>This website contains my family's favorite recipes, with a focus on <b>Dairy-Free</b> and <b>Soy-Free</b> recipes.</p>
        <p>With different food allergies in our household, we focus on using allergy-friendly ingredients for our recipes.</p>

        <h2>Technology</h2>
        <p>This website is built using <a href="https://flask.palletsprojects.com/en/1.1.x/">Flask</a> (web framework written in <a href="https://www.python.org">Python</a>).</p>
        <p>Flask is typically used for developing dynamic website.  For this website, <a href="https://pythonhosted.org/Frozen-Flask/">Frozen-Flask</a> is used to create the static site.</p>
        <p>The static site is then hosted on <a href="https://www.netlify.com">Netlify</a>.</p>
        <br>
        <p>To learn more about how this website is created and deployed, check out the <this></this> blog post on <a href="https://testdriven.io">TestDriven.io:</a></p>
        <a href="https://testdriven.io/blog/static-site-flask-and-netlify/">Generating a Static Site with Flask and Deploying it to Netlify</a>
        <br>
        <br>
        <p>All of the source code for this website can be found on <a href="https://www.gitlab.com/">GitLab</a>:</p>
        <p><a href="https://gitlab.com/patkennedy79/flask-recipe-app">GitLab - Flask Recipe App</a></p>

        <h2>Contact</h2>
        <p>If you'd like to reach out to me to discuss these recipes or to discuss how this website is created: <a href="mailto:pkennedy@hey.com">pkennedy@hey.com</a></p>
    </div>

</div>
{% endblock %}

project/blog/templates/blog/air_fryer.html
{% extends "blogpost.html" %}

{% block title %}
<h1>Thoughts on Air Fryers After Owning For One Year</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on December 28th, 2020</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/air_fryer.jpg') }}"
  alt="Air Fryer"
  class="blogpost__image" />
{% endblock %}

{% block article %}
<p>After having an air fryer for one year, I can say that I'm really glad to have it.  It's a great kitchen accessory, but I've found that I use it mostly for re-heating food and for making side dishes.</p>
<p>I think air fryers are AMAZING at re-heating leftovers!  Heating up leftovers in an air fryer is sooo much better than using a microwave.  Here are some of my favorite foods to re-heat in the air fryer:</p>
<ul>
    <li>Pizza</li>
    <li>Grilled chicken</li>
    <li>Chicken tenders</li>
    <li>Potato wedges</li>
    <li>French fries</li>
    <li>Sauteed vegetables</li>
</ul>
<p>I also think that cooking frozen french fries and onion rings in the air fryer is great.  They come out even better than putting them in the over.  Plus, there is the advantage of not having to wait to pre-heat an oven!</p>
<p>I've tried making chicken tenders from scratch in the air fryer and they come out... not great.  They are cooked all the way through, but they are not super crunchy like you get with actually frying them.  It's a healthier option, but I prefer eating less of the fried version.</p>
<p>Overall, I definitely recommend getting an air fryer, as it's a product that I use multiple times per week.  I was quite apprehensive about buying an air fryer, as I thought it would be a useless new gadget (like I found the Instant Pot to be).  However, I think it's a great tool to have in the kitchen.</p>
<p>The air fryer that I have is the <a href="https://www.usa.philips.com/c-p/HD9650_96/premium">Philips Air Fryer XXL</a> (non-affiliate link).</p>
{% endblock %}

project/blog/templates/blog/blog.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blog_style.css') }}">
{% endblock %}

{% block content %}
<div class="blog-container">

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/kitchenaid_mixer.jpg') }}"
          alt="Kitchenaid Mixer"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <h2>Why I Love my Kitchenaid Stand Mixer</h2>
            <p>The Kitchenaid stand mixer is such a versatile kitchen tool for making lots of different recipes.</p>
            <p class="blog-post-card__date">Published on January 21th, 2021</p>
        </div>
        <div class="blog-post-card__link">
            <a href="{{ url_for('blog.posts', blog_title='kitchenaid_mixer') }}">Read Article</a>
        </div>
    </div>

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/measuring_cups.jpg') }}"
          alt="Measuring Cups"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <h2>Why I Love having Lots of Measuring Cups</h2>
            <p>I have so many measuring cups and I use them everyday!</p>
            <p class="blog-post-card__date">Published on January 8th, 2021</p>
        </div>
        <div class="blog-post-card__link">
            <a href="{{ url_for('blog.posts', blog_title='measuring_cups') }}">Read Article</a>
        </div>
    </div>

    <div class="blog-post-card card-overlay">
        <img
          src="{{ url_for('static', filename='img/air_fryer.jpg') }}"
          alt="Air Fryer"
          class="blog-post-card__image" />
        <div class="blog-post-card__body">
            <h2>Thoughts on Air Fryers After Owning  For One Year</h2>
            <p>I've had an air fryer for one year and I recommend getting one!</p>
            <p class="blog-post-card__date">Published on December 28th, 2020</p>
        </div>
        <div class="blog-post-card__link">
            <a href="{{ url_for('blog.posts', blog_title='air_fryer') }}">Read Article</a>
        </div>
    </div>

</div>
{% endblock %}

project/blog/templates/blog/blogpost_starter.html
{% extends "blogpost.html" %}

{% block title %}
<h1>...</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on January 7th, 2021</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/kitchenaid_mixer.jpg') }}"
  alt="Kitchenaid Mixer"
  class="blogpost__image" />
{% endblock %}

{% block article %}
<p>...</p>
<p>...</p>
{% endblock %}

project/blog/templates/blog/kitchenaid_mixer.html
{% extends "blogpost.html" %}

{% block title %}
<h1>Why I Love the Kitchenaid Stand Mixer</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on January 21th, 2021</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/kitchenaid_mixer.jpg') }}"
  alt="Kitchenaid Mixer"
  class="blogpost__image" />
{% endblock %}

{% block article %}
<p>The Kitchenaid stand mixer is such a versatile kitchen appliance, especially when it comes to baking.  It's just perfect for making cookies, cakes, and cupcakes.</p>
<p>Now that I've started making bread at home, I use the stand mixer with the hook attachment for kneading dough.  It makes making bread so much easier, as kneading dough for 5-10 minutes by hand is hard work.</p>
<p>I recently bought some attachments for making fresh pasta: <a href="https://www.kitchenaid.com/countertop-appliances/stand-mixers/attachments/p.3-piece-pasta-roller-and-cutter-set.ksmpra.html?productcategory=stand_mixer_attachment&cmp=kad%253Awp_sda%25257C01%25257C00118%25257Czz%25257Csh%25257Ct02%25257Cp10%25257Czz%25257Cv04_kasa_ppc%253Aga%253Aps%253Atxt%253Atxt%253Acpc%253Ashop_smartshop%253Ana%253Ana%253A10502427779%253A105389855978%253Ac&gclid=EAIaIQobChMIw8OezNOy7gIVwRrnCh1k9AHGEAQYAiABEgJ7HvD_BwE&gclsrc=aw.ds">Pasta Roller & Cutter Set</a>:</p>
<div class="article__image">
  <img
    src="{{ url_for('static', filename='img/kitchenaid_mixer_pasta.jpg') }}"
    alt="Kitchenaid Mixer"
    class="blogpost__image" />
</div>
<p>Making fresh pasta at home is a good amount of work, but it's really fun to make different types of pasta besides spaghetti.</p>
{% endblock %}

project/blog/templates/blog/measuring_cups.html
{% extends "blogpost.html" %}

{% block title %}
<h1>Why I Love Having Lots of Measuring Cups</h1>
{% endblock %}

{% block date %}
<p class="blogpost__date">Published on January 8th, 2021</p>
{% endblock %}

{% block image %}
<img
  src="{{ url_for('static', filename='img/measuring_cups.jpg') }}"
  alt="Measuring Cups"
  class="blogpost__image" />
{% endblock %}

{% block article %}
<p>I have a collection of measuring cups and I use them almost every day!</p>
<p>I've found that measuring cups are great for lots of things in the kitchen besides measuring, such as:</p>
<ul>
    <li>Use as a small mixing bowl</li>
    <li>Use for scrambling eggs</li>
    <li>Use of melting butter in the microwave</li>
    <li>Use as small bowls when pouring into a stand mixer</li>
</ul>
<p>I have found three sizes of measuring cups to be ideal:</p>
<ul>
    <li>4 Cups (large)</li>
    <li>2 Cups (medium)</li>
    <li>1 Cup (small)</li>
</ul>
<p>The brand of measuring cups that I like is Pyrex.  There is a set of 3 Pyrex measuring cups available for purchase, such as from Target: <a href="https://www.target.com/p/pyrex-measuring-cup-set-3-piece/-/A-17211692?ref=tgt_adv_XS000000&AFID=google_pla_df&fndsrc=tgtao&DFA=71700000012510685&CPNG=PLA_Kitchen%2BShopping&adgroup=SC_Kitchen&LID=700000001170770pgs&LNM=PRODUCT_GROUP&network=g&device=c&location=9031927&targetid=pla-306109337934&ds_rl=1246978&ds_rl=1247068&ds_rl=1248099&gclid=EAIaIQobChMI6ab4nMyy7gIVZyCtBh1QegPBEAQYASABEgItCfD_BwE&gclsrc=aw.ds">Pyrex Measuring Cup Set 3 piece</a> (non-affiliate link).</p>
{% endblock %}